CREATE TABLE CLIENT (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL
);

CREATE TABLE ADDRESS (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    clientId VARCHAR(36),
    address VARCHAR(100) NOT NULL,
    suburb VARCHAR(100),
    number INTEGER,
    unit INTEGER,
    state VARCHAR(3)
);

ALTER TABLE ADDRESS
    ADD FOREIGN KEY (clientId)
    REFERENCES CLIENT(id);